---
title: "Practice 3: Calculus"
format: 
    html:
        toc: true
        toc-location: right
execute:
    echo: false
---

## 1. Find if exists the limit of the sequence as $n \to \infty$

1. $\dfrac{1}{n^2}$
2. $\dfrac{n^2}{2-n^3}$
3. $(0.99)^n$
4. $(1.01)^n$
5. $\sin(\pi n)$

Romantic [interpretation](https://preview.redd.it/zyxtnv0lz0061.jpg?width=640&crop=smart&auto=webp&s=18b057185561e89c19dbb3eaa94a80ce1f2737be) of 3 and 4


## 2. Derivatives
Calculate $f'(x)$

1. $x^2 + 4$
2. $3x^4 - \dfrac{1}{x}$
3. $5 \sin^2(x)$
4. $x e^{x}$

## 3. TanH derivative

Calculate the derivative of tangent hyperbolic function $f(x) = \tanh(x) = \dfrac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$.

Here is the plot:
```{python echo=false}
import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(-5, 5, 100)

y = np.tanh(x)

plt.plot(x, y, label='tanh(x)')
plt.title('Tangent Hyperbolic Function')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.axhline(0, color='black', lw=0.5, ls='--')
plt.axvline(0, color='black', lw=0.5, ls='--')
plt.legend()
```

## 4. Minima, Maxima 
Let $f : [-1,2] \to \mathbb{R},\; x \mapsto \exp\!\bigl(x^{3}-2x^{2}\bigr)$

(a) Compute $f'$  

(b) Plot $f$ and $f'$ with R  

(c) Find all possible candidates $x^*$ for maxima and minima.
*Hint:*  $\exp$ is a strictly monotone function.  

(d) Compute $f''$  

(e) Determine if the candidates are local maxima, minima, or neither.  

(f) Find the global maximum and global minimum of $f$.


## 5. Taylor Series
Find the Taylor polynomial of the function $f(x) = \sin(x)$ around $x = 0$.

## 6. Signed area
What is the signed area between the curve $f(x) = x^2$ and the x-axis on the interval $[-1, 1]$?

1. $2 - 4x$
2. $x^2 + 2$
3. $e^{-x}$
4. $\sin(x)$

## 7. Convexity
Consider two convex functions $f, g : \mathbb{R} \to \mathbb{R}$.

(a) Show that $f + g : \mathbb{R} \to \mathbb{R},\, x \mapsto f(x) + g(x)$ is convex.

(b) Now, assume that $g$ is additionally non‑decreasing, i.e.\ $g(y) \ge g(x)$ for all $x \in \mathbb{R}$ and all $y \in \mathbb{R}$ with $y > x$. Show that $g \circ f$ is convex.
