.PHONY: push                     # single target


ifeq ($(OS),Windows_NT)          # any flavour of Windows
  TIMESTAMP := $(shell powershell -NoLogo -NoProfile -Command "Get-Date -Format 'yyyy-MM-dd HH:mm'")
else                             # Linux / macOS / WSL
  TIMESTAMP := $(shell date '+%Y-%m-%d %H:%M')
endif

msg    ?= rendering $(TIMESTAMP) # override with  msg="your text"
render ?= true                   # override with  render=false

push:
ifeq ($(render),true)
	@echo "1. Running quarto render 🧀"
	@quarto render
else
	@echo "1. Skipping quarto render"
endif
	@echo "2. Staging changes 🧀🧀"
	@git add .
	@echo "3. Committing with message: '$(msg) 🧀🧀🧀'"
	@git commit -m "$(msg)"
	@echo "4. Pushing to remote 🧀🧀🧀🧀"
	@git push
	@echo "5. Done 🧀🧀🧀🧀"
