---
title: "Homework Problems 1 (Vectors)"
format: html
---

<center>
  <span style="font-size: large;">Homework Problems 1 (Vectors)</span>
</center>

---

## Problem 1 (Vector algebra)

The following vectors are given:

$$
\mathbf{a}= \begin{bmatrix} 3 \\ -1 \\ 2 \end{bmatrix}, \qquad \mathbf{b}=\begin{bmatrix} 2 \\ 4 \\ -5 \end{bmatrix}, \qquad \mathbf{c} = \begin{bmatrix} 5 \\ 6.5 \\ -7 \end{bmatrix}.
$$

Find the values of:

- **a)** \(\mathbf{a}+\mathbf{b}\),
- **b)** \(\mathbf{a}+\mathbf{b}-\mathbf{c}\),
- **c)** \(\mathbf{a}^T+\mathbf{b}^T-\mathbf{c}^T\),
- **d)** \(3\mathbf{a}^T+4\mathbf{b}^T-2\mathbf{c}^T\),
- **e)** \(6\mathbf{a}^T+8\mathbf{b}^T-4\mathbf{c}^T\),
- **f)** \(\mathbf{a} \cdot \mathbf{b}\),
- **g)** \((3\mathbf{a} - 6\mathbf{b}) \cdot \mathbf{c}\),
- **h)** \(\mathbf{a} \cdot (4\mathbf{a}^T - \mathbf{b}^T)^T\).


---

## Problem 2 (Translation office)

A translation office translated 
\[
\mathbf{a}=[24,\, 17,\, 9,\, 13]
\]
documents from English, French, German and Russian, respectively. For each language, it takes about 
\[
\mathbf{b}=[5,\, 10,\, 11,\, 7]
\]
minutes to translate one page.

- How much time did they spend translating in total? How much did each of the translators spend on average if there are 4 translators in the office?  
- Write an expression for this amount in terms of the vectors \(\mathbf{a}\) and \(\mathbf{b}\).

---

## Problem 3 (Norms)

Calculate the Manhattan (L1) and Euclidean (L2) norms of the following vectors:

- **a)** \(\mathbf{a}= \begin{bmatrix} 2 \\ -9 \\ 3 \end{bmatrix}\),
- **b)** \(\mathbf{a}-2\mathbf{b}\), where 
  \[
  \mathbf{a}= \begin{bmatrix}3 \\ 4 \\ 1 \\ 0\end{bmatrix},\quad \mathbf{b}= \begin{bmatrix}4 \\ 5 \\ -2 \\ -1\end{bmatrix},
  \]
- **c)** \(-3\mathbf{c}\), where 
  \[
  \mathbf{c}= \begin{bmatrix}2 \\ -5 \\ 6\end{bmatrix}.
  \]

---

## Problem 4 (angle between vectors)

Find the angles between the following vectors:

- **a)** \(\mathbf{a}= \begin{bmatrix} 2 \\ 1 \\ 1 \end{bmatrix}\) and \(\mathbf{b}= \begin{bmatrix} 1 \\ -3 \\ 3 \end{bmatrix}\),
- **b)** The vectors \(\mathbf{a}\) and \(\mathbf{c}\) from the previous problem.

---

## Problem 5 (Matrix vector product)

What vectors do you get by applying the matrix

$$
A = \begin{bmatrix} 3 & -3 \\ 3 & 3 \end{bmatrix}
$$

to the vectors:

- **a)** \(\mathbf{a}=\begin{bmatrix} 1 \\ 0 \end{bmatrix}\),
- **b)** \(\mathbf{b}=\begin{bmatrix} 0 \\ 1 \end{bmatrix}\),
- **c)** \(\mathbf{c}=\begin{bmatrix} 1 \\ 1 \end{bmatrix}\)?

*(Additional:)* Draw the vectors before and after multiplying with \(A\). What can you say visually about the matrix? Can you guess how it will act on the vector \([2 \quad -2]\)?

---

## Problem 6 (Matrix algebra)

Compute the following products:

- **a)** \(AB\), where 
  \[
  A=\begin{bmatrix} 6 & 5 \\ -2 & 7 \end{bmatrix},\quad B=\begin{bmatrix} -5 & 3 \\ 1 & 4 \end{bmatrix},
  \]
- **b)** \((A-B)(A+B)\), where 
  \[
  A=\begin{bmatrix} 2 & 2 & 4 \\ -3 & -2 & 4 \\ -2 & 0 & 2 \end{bmatrix},\quad B=\begin{bmatrix} 2 & 1 & 3 \\ -1 & 2 & 2 \\ 1 & 4 & -1 \end{bmatrix},
  \]
- **c)** \(A^2 - B^2\) with the same \(A\) and \(B\) as in **b)**.

---

## Problem 7 (Geometric interpretation of matrix multiplication)

Consider the following matrix (called the *shear matrix*):

$$
S = \begin{bmatrix} 1 & 1 \\ 0 & 1 \end{bmatrix}
$$

Answer the following:

- **a)** What do you get if you apply \(S\) to the vector \([0 \quad 1]\)?
- **b)** What do you get if you apply \(S\) again on the result of the previous point?
- **c)** What if you apply \(S\) one more time?
- **d)** What do you think happens when we apply \(S\) 100 times to that vector?
- **e)** Can you compute \(S^{100}\)?

---

## Problem 8 (Vector space)

Determine whether or not the following sets (with usual addition and scalar multiplication) are vector spaces:

- **a)** 
  \[
  A = \left\{ \begin{bmatrix} a \\ 0 \end{bmatrix} \mid a\in\mathbb{R} \right\},
  \]
- **b)** 
  \[
  B = \left\{ \begin{bmatrix} a \\ -a \end{bmatrix} \mid a\in\mathbb{R} \right\}.
  \]
- **c)** \(A = \mathbb{N}\),
- **d)** 
  \[
  B = \left\{ \begin{bmatrix} a \\ 1 \end{bmatrix} \mid a\in\mathbb{R} \right\}.
  \]

*Hint:* If you want to proof that something is *not* a vector space you can try to show that there are some "bad" elements, such that if we add them or multiply them by a scalar (not necessarily positive), the result would not belong to the set.
