---
title: "Practice 2: Matrices"
format: html
---

## Exercises

1. Determinant: \( \text{det}(AB) = \text{det}(A) \cdot \text{det}(B) \)
2. Determinant using Leibniz method.
3. Matrix interpretation geometrically.
4. Finding the inverse geometrically and numerically.
5. Linear dependence / independence.
6. Show that a set forms a basis.
7. Calculate the rank of a matrix.
8. Eigenvalues and eigenvectors.
9. \( \text{det} = \text{product of eigenvalues}, \quad \text{trace} = \text{sum of eigenvalues} \)
10. Solving systems of linear equations (SLE).

symmetric matrix eigenvectors orthogonal?
condition number?

# Determinants
- Prove that $\text{det}(B^{-1}AB) = \text{det}(A)$ if $B$ is invertible.
- Suppose $Q$ is a $3 \times 3$ real matrix such that $Q^T Q = I$. What values can $\text{det}(Q)$ take?.

# Linear dependence, basis, rank
We have the following dataset of cheeses 

| **Cheese** | **Price in USD** | **Price in AMD** | **Year Made** | **Years Waited** | **Year Eaten** |
|:-----------:|:----------------:|:----------------:|:----------------------:|:----------------:|:--------------:|
| $v_1\$     | 300              | 150,000          | 2012                   | 5                | 2017           |
| $v_2$     | 450              | 225,000          | 2010                   | 7                | 2018           |
| $v_3$     | 350              | 175,000          | 2014                   | 3                | 2017           |
| $v_4$     | 400              | 200,000          | 2013                   | 4                | 2018           |
| $v_5$     | 280              | 140,000          | 2011                   | 6                | 2016           |

**Tasks**
1. Determine the maximum possible dimension of the subspace spanned by $v_1, \dots, v_5$.
2. Identify a maximal linearly independent subset (a basis) of these vectors.
3. Which features would you use in a Machine Learning and why? If not all, why?

# $n$-th power of a matrix (eigendecomposition)
Compute $n$-th power of the matrix
$$
A = \begin{pmatrix}
    5 & 8 \\
    2 & 5
\end{pmatrix}
$$

```{=html}
<object data="power_of_matrix.pdf" type="application/pdf" width="100%" height="100%" style="min-height:100vh;">
    <p>It appears you don't have a PDF plugin for this browser.
    No biggie... you can <a href="power_of_matrix.pdf">click here to
    download the PDF file.</a></p>
</object>
```

